 version: '3'
 services:
    selenium-hub:
    image:selenium/hub

    ports:

    -"4442-4444:4442-4444"

   networks:
     
      -grid

    node-chrome:

    image:selenium/node-chrome
     
    environment:

      -e SE_EVENT_BUS_HOST=selenium-hub
      -e SE_EVENT_BUS_PUBLISH_PORT=4442 
      -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      
    networks:
       grid 

    ode-chrome:

    image:selenium/node-firefox
     
    environment:

      -e SE_EVENT_BUS_HOST=selenium-hub
      -e SE_EVENT_BUS_PUBLISH_PORT=4442 
      -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443    

    networks:
        grid   

     driver:bridge   
       